#ifndef QUERYWIDGET_H
#define QUERYWIDGET_H

#include <QWidget>
#include <QSplitter>
#include <QTextCursor>
#include <QPlainTextEdit>
#include <memory>
#include <QJsonObject>

class DbConnection;
class TableModel;
class SqlSyntaxHighlighter;
class QMenu;
class FindAndReplacePanel;
class QVBoxLayout;
class DataTable;
class CodeEditor;
class QCompleter;
class QTimer;

class QueryWidget : public QSplitter
{
    Q_OBJECT
public:
    explicit QueryWidget(QWidget *parent = nullptr);
    explicit QueryWidget(DbConnection *connection, QWidget *parent = nullptr);
    ~QueryWidget();
    const QString& fileName() { return _fn; }
    // Tab caption without the modification mark. Unlike the file name it also
    // survives for the tabs having no file behind them (created manually or by
    // F4), which would otherwise lose their caption on the first edit.
    const QString& title() const { return _title; }
    void setTitle(const QString &title, bool isAuto = false)
    {
        _title = title;
        _titleIsAuto = isAuto;
    }
    // an autogenerated title follows the database, a file/object name never does
    bool titleIsAuto() const { return _titleIsAuto; }
    // the tab is an F4 result nobody has touched yet, hence reusable
    bool isGeneratedScript() const { return _generatedScript && !isModified(); }
    void setGeneratedScript(bool v) { _generatedScript = v; }
    bool openFile(const QString &fileName, const QString &encoding);
    bool saveFile(const QString &fileName, const QString &encoding = QString());
    QString encoding() { return _encoding; }
    DbConnection* dbConnection() { return _connection.get(); }
    /// The same link, shareable - the file search borrows it to highlight the
    /// scripts it finds and to clone a connection for the tabs it opens.
    const std::shared_ptr<DbConnection>& sharedDbConnection() const { return _connection; }
    void setDbConnection(DbConnection *connection);
    void ShowFindPanel(FindAndReplacePanel *panel);
    /// Attaches a highlighter built for the connection's dbms. Pass force=true
    /// to rebuild it even when the connection has not changed - the dictionary
    /// is read from hl.conf at construction, so that is what picks up an edited
    /// (or newly shadowed) one.
    void highlight(std::shared_ptr<DbConnection> con = nullptr, bool force = false);
    void dehighlight();
    void rehighlight();
    bool is_sql_hl(QPlainTextEdit *ed);

    void setReadOnly(bool ro = true);
    bool isReadOnly() const;
    void clear();
    bool isModified() const;
    void setModified(bool m = true);
    void setTextCursor(const QTextCursor &cursor);
    /// Marks a range as "the place you were sent to" (a file search hit) in the
    /// underlying editor, if it is a code editor. See CodeEditor::setMatchHighlight -
    /// the point is a mark that stays visible while the focus is in the results tree.
    void setMatchHighlight(const QTextCursor &range, const QColor &color = QColor());
    void clearMatchHighlight();
    QString toPlainText();
    QTextCursor textCursor() const;
    QTextDocument* document() const;
    QWidget* editor() const;
    void setPlainText(const QString &text);
    void setHtml(const QString &html);
    void setQuerySettings(QJsonObject &querySettings);
    bool isTimerActive() const;
    void stopTimer();
    void executeOnTimer(const QString &query, int interval);
    // Runs a query on behalf of the user. Queries must be started through this
    // method rather than through dbConnection() directly: it raises the flag
    // that makes the connection's output count as this query's result.
    void execute(const QString &query);

signals:
    void sqlChanged();
    // Whatever the connection has to say while no query of ours is running.
    // It is not a query result, so it does not belong to the messages pane -
    // MainWindow puts it into the log.
    void message(QString msg);
    void error(QString msg);

public slots:
    void onMessage(const QString &text);
    void onError(const QString &text);
    void fetched(DataTable *table);
    void clearResult();
    void onCompleterRequest();
    void onScriptObjectRequest();
    //void onCustomGridContextMenuRequested(const QPoint & pos);
    //void on_customEditorContextMenuRequested(const QPoint & pos);

private:
    QTimer *_timer;
    QJsonObject _querySettings;
    QString _fn;
    QString _title;
    bool _titleIsAuto = false;
    bool _generatedScript = false;
    // A query of ours is in flight. The connection reports asynchronously, so
    // its live queryState() is already Inactive by the time a queued message
    // arrives - only a flag raised at the start of the run can tell the query's
    // own output from everything else.
    bool _queryActive = false;
    // formats a message for the shared log, naming the tab it came from
    QString logMessage(const QString &text) const;
    QString _encoding;
    QWidget *_editor;
    QPlainTextEdit *_messages;
    QSplitter *_resSplitter;
    std::shared_ptr<DbConnection> _connection;
    SqlSyntaxHighlighter *_highlighter;
    QVBoxLayout *_editorLayout;
    QMenu *_resultMenu;
    QAction *_actionCopy;
    void log(const QString &text, QColor color);
    static QCompleter *completer();
};

#endif // QUERYWIDGET_H
