#ifndef QUERYWIDGET_H
#define QUERYWIDGET_H

#include <QWidget>
#include <QSplitter>
#include <QTextCursor>
#include <QPlainTextEdit>
#include <QPair>
#include <memory>
#include <QJsonObject>

class DbConnection;
class TableModel;
class SqlSyntaxHighlighter;
class QMenu;
class FindAndReplacePanel;
class QVBoxLayout;
class DataTable;
class CodeEditor;
class QCompleter;
class QTimer;

class QueryWidget : public QSplitter
{
    Q_OBJECT
public:
    explicit QueryWidget(QWidget *parent = nullptr);
    explicit QueryWidget(DbConnection *connection, QWidget *parent = nullptr);
    ~QueryWidget();
    const QString& fileName() { return _fn; }
    // Tab caption without the modification mark. Unlike the file name it also
    // survives for the tabs having no file behind them (created manually or by
    // F4), which would otherwise lose their caption on the first edit.
    const QString& title() const { return _title; }
    void setTitle(const QString &title, bool isAuto = false)
    {
        _title = title;
        _titleIsAuto = isAuto;
    }
    // an autogenerated title follows the database, a file/object name never does
    bool titleIsAuto() const { return _titleIsAuto; }
    // the tab is an F4 result nobody has touched yet, hence reusable
    bool isGeneratedScript() const { return _generatedScript && !isModified(); }
    void setGeneratedScript(bool v) { _generatedScript = v; }
    bool openFile(const QString &fileName, const QString &encoding);
    bool saveFile(const QString &fileName, const QString &encoding = QString());
    QString encoding() { return _encoding; }
    /// Tells the widget which file the text it *shows* comes from, when that
    /// file is not one of its own (fileName() is empty for the content pane -
    /// it never opens or saves anything, the window hands it a file search hit
    /// to preview). Only codeLocation() reads this. \a root is the folder the
    /// path is to be reported relative to - the folder that was searched -
    /// empty for an absolute one.
    void setShownFile(const QString &fileName, const QString &root = QString());
    DbConnection* dbConnection() { return _connection.get(); }
    /// The same link, shareable - the file search borrows it to highlight the
    /// scripts it finds and to clone a connection for the tabs it opens.
    const std::shared_ptr<DbConnection>& sharedDbConnection() const { return _connection; }
    void setDbConnection(DbConnection *connection);
    void ShowFindPanel(FindAndReplacePanel *panel);
    /// Attaches a highlighter built for the connection's dbms. Pass force=true
    /// to rebuild it even when the connection has not changed - the dictionary
    /// is read from hl.conf at construction, so that is what picks up an edited
    /// (or newly shadowed) one.
    void highlight(std::shared_ptr<DbConnection> con = nullptr, bool force = false);
    void dehighlight();
    void rehighlight();
    bool is_sql_hl(QPlainTextEdit *ed);

    void setReadOnly(bool ro = true);
    bool isReadOnly() const;
    void clear();
    bool isModified() const;
    void setModified(bool m = true);
    void setTextCursor(const QTextCursor &cursor);
    /// Marks a range as "the place you were sent to" (a file search hit) in the
    /// underlying editor, if it is a code editor. See CodeEditor::setMatchHighlight -
    /// the point is a mark that stays visible while the focus is in the results tree.
    void setMatchHighlight(const QTextCursor &range, const QColor &color = QColor());
    void clearMatchHighlight();
    QString toPlainText();
    QTextCursor textCursor() const;
    /// [start, end) of the SQL statement at the caret, ignoring any current
    /// selection - what Ctrl+Return sends when there is none, and what
    /// Ctrl+Shift+A selects to preview that. {-1, -1} if no dictionary-driven
    /// lexer is available for this connection (see SqlLexer::sharedFor()).
    QPair<int, int> currentStatementBounds();
    QTextDocument* document() const;
    QWidget* editor() const;
    void setPlainText(const QString &text);
    void setHtml(const QString &html);
    void setQuerySettings(QJsonObject &querySettings);
    bool isTimerActive() const;
    void stopTimer();
    void executeOnTimer(const QString &query, int interval);
    // Runs a query on behalf of the user. Queries must be started through this
    // method rather than through dbConnection() directly: it raises the flag
    // that makes the connection's output count as this query's result.
    void execute(const QString &query);
    /// An aside about the run the user has just asked for, in the messages pane
    /// where the answer was expected ("empty query", and the like). A run that
    /// produces nothing at all reads as a broken application, so the absence of
    /// a result is itself a result and belongs next to the real ones - unlike
    /// everything the connection says on its own, which goes to the log.
    void note(const QString &text);
    /// A transient aside about something that is not a query run at all (no
    /// statement to select, no object to script): the status bar, never the
    /// messages pane, where it would read as the output of the query shown
    /// there. Falls back to the pane only where there is no status bar.
    void status(const QString &text);

    /// "Where is this code", ready to be pasted into an ai agent's prompt:
    /// the file behind the editor's text followed by the line the caret is on
    /// ("path/to/file.sql:42"), or by the range a selection covers
    /// ("path/to/file.sql:42-58"). Empty when the text belongs to no file on
    /// disk - the script of a database object, a tab never saved, the html
    /// content pane - in which case there is nothing to point at.
    ///
    /// The path is absolute for a file opened in a tab, and relative to the
    /// folder that was searched when the text is a file search hit shown in the
    /// preview pane: those results are read as a set, and the root they share
    /// is the project an agent will be pointed at.
    QString codeLocation() const;

signals:
    void sqlChanged();
    // Whatever the connection has to say while no query of ours is running.
    // It is not a query result, so it does not belong to the messages pane -
    // MainWindow puts it into the log.
    void message(QString msg);
    void error(QString msg);

public slots:
    void onMessage(const QString &text);
    void onError(const QString &text);
    void fetched(DataTable *table);
    void clearResult();
    void onCompleterRequest();
    void onScriptObjectRequest();
    void onExecuteStatementRequest();
    void onSelectStatementRequest();
    /// Ctrl+Shift+C and the matching context menu item: the place being read,
    /// as "file:line" (see codeLocation()), onto the clipboard.
    void onCopyCodeLocationRequest();
    /// Appends the editor's own commands to the standard context menu it just
    /// built (CodeEditor::contextMenuRequest).
    void onEditorContextMenu(QMenu *menu);
    //void onCustomGridContextMenuRequested(const QPoint & pos);
    //void on_customEditorContextMenuRequested(const QPoint & pos);

private:
    QTimer *_timer;
    QJsonObject _querySettings;
    QString _fn;
    /// The file the *shown* text comes from when it is not the widget's own
    /// (the content pane previewing a file search hit), and the folder its path
    /// is reported relative to. See setShownFile().
    QString _shownFile;
    QString _shownFileRoot;
    QString _title;
    bool _titleIsAuto = false;
    bool _generatedScript = false;
    // A query of ours is in flight. The connection reports asynchronously, so
    // its live queryState() is already Inactive by the time a queued message
    // arrives - only a flag raised at the start of the run can tell the query's
    // own output from everything else.
    bool _queryActive = false;
    // The run ended without an answer and may or may not have been executed
    // (DbConnection::outcomeUnknown). Reporting it as "done" would invite a
    // retry, which is the one thing that must not be automatic here.
    bool _outcomeUnknown = false;
    // formats a message for the shared log, naming the tab it came from
    QString logMessage(const QString &text) const;
    QString _encoding;
    QWidget *_editor;
    QPlainTextEdit *_messages;
    QSplitter *_resSplitter;
    std::shared_ptr<DbConnection> _connection;
    SqlSyntaxHighlighter *_highlighter;
    QVBoxLayout *_editorLayout;
    QMenu *_resultMenu;
    QAction *_actionCopy;
    void log(const QString &text, QColor color);
    static QCompleter *completer();
};

#endif // QUERYWIDGET_H
